[env:waveshare-esp32-s3-touch-lcd-1_85]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D STEEDPILOT_FIRMWARE

lib_deps =
    moononournation/GFX Library for Arduino

